version: '3.8'

services:
  db:
    image: postgres:15
    container_name: repsy-postgres
    restart: always
    environment:
      POSTGRES_DB: repsydb
      POSTGRES_USER: repsyuser
      POSTGRES_PASSWORD: repsypass
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: repsy-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/repsydb
      SPRING_DATASOURCE_USERNAME: repsyuser
      SPRING_DATASOURCE_PASSWORD: repsypass
    ports:
      - "8080:8080"

volumes:
  pgdata:
