version: '3.8'

services:
  db:
    image: postgres
    container_name: repsy_postgres
    read_only: true
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=user123
        - POSTGRES_DB=repsyDb
    expose:
        - "54322"
    ports:
        - "54322:54322"
    tmpfs:
        - /tmp
        - /run
        - /run/postgresql
    volumes:
        - postgres-volume:/var/lib/postgresql/data
    command: -p 54322

  app:
    build: .
    container_name: repsy-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:54322/repsyDb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
    ports:
      - "8080:8080"

volumes:
  postgres-volume: